logging:
  level:
    edu.stanford.slac.core_build_system: ${CBS_LOG_LEVEL:DEBUG}

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: 'cbs'
  ldap:
    urls: ${CBS_LDAP_URI:ldap://localhost:8389}
    base: ${CBS_LDAP_BASE:dc=sdf,dc=slac,dc=stanford,dc=edu}
  data:
    mongodb:
      uri: ${CBS_MONGODB_URI:mongodb://cbs:cbs@localhost:27017/cbs?authSource=cbs}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: ${CBS_MAX_POST_SIZE:100MB}
      max-request-size: ${CBS_MAX_POST_SIZE:100MB}
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: processing-task-

edu:
  stanford:
    slac:
      core-build-system:
        github-app-id: ${CBS_GH_APP_ID}
        github-app-installation-id: ${CBS_GH_APP_INST_ID}
        github-app-private-key: ${CBS_GH_APP_PRIV_KEY}
        # this is the path where the scratch build is stored and that si mount within the path '/mnt' within the k8s pod
        build-fs-root-directory: ${CBS_BUILD_FS_ROOT_DIR:/tmp/host-tmp}
        build-scratch-root-directory: ${CBS_BUILD_SCRATCH_ROOT_DIR:cbs-build-root}
        #/mnt/build this is will be the path where the build scratch direction from fs will bem mounted
        build-pod-mount-point: ${CBS_BUILD_POD_MOUNT_POINT:/mnt}
        artifact-root-directory: ${CBS_ARTIFACT_ROOT_DIR:/tmp/cbs-artifact}
        k8s-build-namespace: ${CBS_K8S_BUILD_NAMESPACE:build-ns}
        build-volume-claim-name: ${CBS_BUILD_VOLUME_CLAIM_NAME:build-scratch-volume-claim}
        builder-group-id: ${CBS_BUILDER_GROUP_ID:}
        builder-user-id: ${CBS_BUILDER_USER_ID:}
        host-name-prefix: ${CBS_HOST_NAME_PREFIX:http://localhost:8080}
      ad:
        eed:
          baselib:
            app-token-prefix: ${spring.application.name}
            app-token-jwt-key: ${CBS_APP_TOKEN_JWT_KEY:token-header-key}
            user-header-name: ${CBS_AUTH_HEADER:x-vouch-idp-accesstoken}
            oauth-server-discover: ${CBS_OIDC_CONFIGURATION_ENDPOINT:https://dex.slac.stanford.edu/.well-known/openid-configuration}
            root-user-list: ${CBS_ROOT_USERS}
            root-authentication-token-list-json: ${CBS_ROOT_AUTHENTICATION_TOKEN_JSON:[]}
          mongodb:
            db_admin_uri: ${CBS_ADMIN_MONGODB_URI:mongodb://admin:admin@localhost:27017/?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

# swagger-ui custom path
springdoc:
  version: 1.0.0
  title: 'Core Build System API'
  description: 'Core Build System API for the Accelerator Division at SLAC National Accelerator Laboratory'
  contact:
    name: 'API Support'
    url: 'https://confluence.slac.stanford.edu/display/EEDWAD/EED+Web+Applications'
    email: 'bisegni@sac.stanford.edu'
  swagger-ui:
    enabled: false
  api-docs:
    path: /api-docs
    version: openapi_3_0

mongock:
  migration-scan-package:
    - edu.stanford.slac.core_build_system.migration
  throw-exception-if-cannot-obtain-lock: true #Default true
  track-ignored: false #Default true
  transaction-enabled: false
  runner-type: initializingbean
  enabled: true #Default true