logging:
  level:
    edu.stanford.slac.core_build_system: DEBUG
    org.springdoc: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true

edu:
  stanford:
    slac:
      core_build_system:

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: 'core-build-system' 

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs