spring:
  ldap:
    embedded:
      base-dn: dc=sdf,dc=slac,dc=stanford,dc=edu
      ldif: classpath:test-ldap-schema.ldif
      port: 8389
      validation:
        enabled: false
  cache:
    type: none
edu:
  stanford:
    slac:
      core-build-system:
        github-app-id: ${CBS_GH_APP_ID}
        github-app-installation-id: ${CBS_GH_APP_INST_ID}
        github-app-private-key: ${CBS_GH_APP_PRIV_KEY}
        github-org-name: ${CBS_GH_ORG_NAME:ad-build-test}
      ad:
        eed:
          baselib:
            root-user-list: ${CWM_ROOT_USERS:user1@slac.stanford.edu}
            app-token-jwt-key: ${CWM_APP_TOKEN_JWT_KEY:dabd148ddd89bf64236b3c2563a54921d95c959dbe6a872be3eefaa2f284a4cb}
            root-authentication-token-list-json: |
              [{"name":"root-token-1","expiration":"2024-12-31"}]
logging:
  level:
    org.springframework.data.mongodb: DEBUG
