apiVersion: v1
kind: Pod
metadata:
  name: builder
spec:
  containers:
    - name: builder-container
      image: busybox
      volumeMounts:
        - mountPath: /mnt
          name: data-volume
  restartPolicy: Never
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: build-scratch-volume-claim